[build-system]
requires = ["setuptools>=62.3", "oldest-supported-numpy", "cython~=3.0", "raysect==0.8.1.*"]
build-backend="setuptools.build_meta"

[tool.ruff]
line-length = 120
include = ["cherab/**/*.py", "demos/**/*.py"]

[tool.ruff.lint]
ignore = [
    "F401",  # ignore unused imports
]

[tool.cython-lint]
max-line-length = 140
